### PR TITLE
Fix sphinx build in source dir

### PR DESCRIPTION
**Pull request by avalentino**
The sphinx documentation cannot be built from the source directory.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
Is this for debian builds? Is the package (pycoast) installed into the environment before building documentation? I think my preference would be to remove the hacky `sys.path` stuff and just require pycoast be installed first.

**Comment by avalentino** [comment]
Yes it is for debian builds, and pycoast is stil not installed.
By the way if you plan to remove the `sys.path` trick I can find an alternative solution do build the debian package.
Please ignore this PR.

**Comment by djhoese** [comment]
I ask because I've generally started to follow the pattern of removing the `sys.path` hack in the libraries that I work on because it avoids the case where the user hasn't installed and built parts of the library like cython extensions or anything else that happens during build time (versioneer or setuptools_scm creating the `<pkg>/version.py` file). If you can find a way to install the package and then run documentation that would be for the best, but let me know if you think of other options that would help.

**Comment by avalentino** [comment]
Thanks.
I already have a workaround (tweaking PYTHONPATH to point to the debian build directory) that I also use in other packages.

**Pull request closed without merging**
