### PR TITLE
Fix for horizontal (merc) and vertical (tmerc) scratches in medium si…

### LINKED ISSUE #23: Pycoast v0.5.2  issue when drawing coastlines
Reference to similar problem in Google Group:
https://groups.google.com/forum/#!searchin/pytroll/pycoast$20lines%7Csort:date/pytroll/tzmtaDuaGD4/kVrY2RZ93gEJ

Hrobjartur Thorsteinsson:
Coastlines need a consistency check that drawn line-segments do not exceed some sort of threshold. We had considered that, but now I think I should add that improvement.

issue

### PR DESCRIPTION
**Pull request by lobsiger**
Fix for horizontal and vertical scratches in medium sized area_extents. Cylindrical projections might
need an additional easy workaround due to the huge Eurasia polygon that spans > 180° longitude.
Exeptions are full globe projections when users set lon_0<>0 which is incompatible with GSHHG.

Fix for meridian lon=0° wrongly identified as dateline suppressing relevant coastlines left and right.

All explanations for scratch problem and a simple test script here:
https://groups.google.com/g/pytroll/c/xTFZW1ptH7s

All explanation for missing coastlines and a simple test script here:
https://groups.google.com/g/pytroll/c/Uz1zE6TpFzE

You asked for it, you got it ...

 - [ ] Closes #23 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by lobsiger** [comment]
@mraspaud please review my one and only PR. Thanks.

**Comment by djhoese** [comment]
You got a github account!

I'm guessing you didn't mean to close this, right?

**Comment by lobsiger** [comment]
Sorry, Dave. Close was the wrong button :-(. It's my first PR after all ...

**Comment by lobsiger** [comment]
Dave and Martin: I have not checked whether this version of my PR works at all as I haven't setup a development branch of satpy. No idea wheter this lint indent style thing is a problem. Please adapt style as necessary ...

**Comment by lobsiger** [comment]
flake8 fail fixed. The failing CodeFactor stuff seems not to be my fault. 
I added an improved script that also can produce vertical scratch lines.

https://groups.google.com/g/pytroll/c/xTFZW1ptH7s

**Comment by djhoese** [comment]
For future reference, I'll paste your script here:

```python
import aggdraw
import pyresample
from PIL import Image
from pycoast import ContourWriterAGG
area_file='/home/eumetcast/EMCtools/pppconfig/opc2.yaml'
# OPC merc areas: opcae, opcaw, opcpe, opcpw. Symmetric: opcaes, opcaws (=opcaw), opcpes, opcpws.
# OPC tmerc areas: opcaet, opcawt, opcpet, opcpwt. All symmetric, Eurasia does not cross equator.
area='opcpw'
area_def = pyresample.load_area(area_file, area)
if area[-1] == 't':
   img = Image.new('RGB', (1776, 995))
   fs = 20
else:
   img = Image.new('RGB', (1776, 1562))
   fs = 30
font = aggdraw.Font('white', '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf', opacity=255, size=fs)
cw = ContourWriterAGG('/home/eumetcast/EMCdata/gshhg-shp')
out_png='/home/eumetcast/EMCdata/products/' + area + '.png'
cw.add_coastlines(img, area_def, resolution='i', outline='gold')
cw.add_rivers(img, area_def, resolution='i',level=3, outline='blue')
cw.add_borders(img, area_def, resolution='i', outline='red')
cw.add_grid(img, area_def, (10., 10.), (2., 2.), font, outline='silver')
img.save(out_png)
```

Note, like my example script in the related issue (https://github.com/pytroll/pycoast/issues/23#issuecomment-1065793716), it is possible to create an area definition in Python. For example scripts that will make it easier for other people to run the script. For now I'll just paste the relevant portion of the YAML:

```yaml
opcpw:
  description: NOAA/OPC Pacific West Mercator (Surface Pressure Overlay, lat_ts=0.0, 175 +/-40)
  projection:
    proj: merc
    ellps: WGS84
    lon_0: 170.0
  shape:
    height: 1562
    width:  1776
  area_extent:
    lower_left_xy: [-3899875.0,  1795000.0]
    upper_right_xy: [5014125.0,  9600000.0]
```

As for the CodeFactor stuff, it is your changes that are triggering this discovery but not something we'll worry about right now. It is basically saying that the method is too complex and should be broken into smaller sub-methods/functions. For now we won't worry about it and @mraspaud or myself will fix it if needed.

I approved the existing tests in the code to run and they look to be passing so that's good. I'm preparing to go on vacation this week and then will be on vacation for about a week so I probably won't have time to test this too much. I do want to say that I appreciate you making a github account and making this pull request. I know it wasn't something you wanted to do or were eager to do, but it means a lot that you are wiling to contribute to the code in a way that makes it easier for us.

**Comment by lobsiger** [comment]
@mraspaud I'll add the tests over the weekend. I have already added tests for 'cities' PR 61 and 'shapefiles' PR 62 using overlays_from_dict(). I'll also add a test for the "Ireland has no coasts" problem of PR 60.  This should be rather easy as I have also published mini scripts for these issues on the google list. Stay tuned ...

**Comment by lobsiger** [comment]
@mraspaud I have added the tests you asked for. I have tested them outside of my forked PyCoast repo and then copied them into the test script and slightly adapted them from functions to methods. So there might be minor issues and flake8 stuff to begin with. I added separate tests for pil and agg. The images below show the output of the pil tests without my PR 59 applied.
no_h_scratch_pil
no_v_scratch_pil
western_shapes_pil
eastern_shapes_pil

**Comment by mraspaud** [comment]
@lobsiger very nice with the new tests, thanks a lot! I can see that indeed flake8 is not totally happy :)

**Comment by lobsiger** [comment]
@mraspaud as I said to Dave lately: CodeFacter shows under 'Details' oder code and probably doesn't test my latest version.
        if np.sign(lons_s1[0]) * np.sign(lons_s1[-1]) == -1 and \
            lons_s1[lons_s1 < 0].min() * lons_s1[lons_s1 > 0].max() < -25000:
            # End points of left side on different side of dateline
should now read
        if np.sign(lons_s1[0]) * np.sign(lons_s1[-1]) == -1 and \
            lons_s1.min() * lons_s1.max() < -25000:
            # End points of left side on different side of dateline

:)

**Comment by mraspaud** [comment]
Yes, codefactor wants us to refactor this code, but I think we can take this in a later PR. This looks good to me, merging now.

**Pull request merged**
