### PR TITLE
Switch to GitHub Actions for CI

### PR DESCRIPTION
**Pull request by djhoese**
This PR does the following:

1. Removes travis config
2. Updates README with new badges to point to github actions and coveralls
3. Remove unittest "suite" function from `test_pycoast`
4. Updates setup.py with python_requires and removes test_suite
5. Removes old bumpversion config
6. Removes 'six' dependency on configparser (we're python 3 only now, no need for this library for one import)
7. Add GitHub actions (based on satpy's) for CI and sdist deployment. It should use the pytroll github organization's secret to upload to PyPI so this should be fine.
8. CI environments use mambaforge (FYI @pnuu @mraspaud)

Note tests include website building with the `-W` flag so it fails if there are any warnings.

### CODE REVIEW

**Comment by djhoese** [comment]
Hm good point. I guess only for consistency. Using mambaforge it probably isn't that slow, but I see what you're saying. I'll get the tests to pass and then switch to pip.

**Comment by mraspaud** [comment]
if you need inspiration, we are using pip in trollflow2's actions

**Comment by djhoese** [comment]
So everything is now passing since I switched back to conda. With pip I think it tried to install aggdraw and freetype from source and this failed or rather it produced different results. I'm not sure if this is something that could be fixed with more aggdraw wheels (no python 3.9 right now), but I'm pretty sure the failures were on python 3.7 which has wheels.

So...point is, it seems that this is ready to go as long as it uses conda. :shrug:

**Review by mraspaud — APPROVED** [review]
LGTM, thanks for taking the time.

**Pull request merged**
