### PR TITLE
Add ability to overlay user specific shapefiles from dict

### PR DESCRIPTION
**Pull request by lobsiger**
This gives the possibility to add user specific shape files as overlays. These must be (lon/lat) and either shape-type polygon or line.
overlays[shapefiles] is a list of dicts that must at least look like {'filename' : '/full_path_to_your/special.shp'}. Polygons can be filled.
Christian Peters uses this for adding administrative boundaries of German 'States' (Bundesländer) on daily weather station images.
I also changed the order in overlays_from_dict():  'grid' should not be added last as it will spoil the text labels of 'cities' and 'points'.

 - [x ] Tests added 
 - [x ] Tests passed

### CODE REVIEW

**Comment by lobsiger** [comment]
@peters77 here is a screen shot from Christian Peters:
germany

**Comment by djhoese** [comment]
This branch now has conflicts with main. Could you try following my instructions in this comment: https://github.com/pytroll/pycoast/pull/60#issuecomment-1119013600 and see if you can get pytroll's main branch merge into this `usr_shps` branch?

**Review by djhoese — APPROVED** [review]
Looks good to me. Thanks.

**Comment by lobsiger** [comment]
@djhoese thanks for merging this. I will now once again merge main into fix_cities (if necessry at all) and then comment my findings regarding test data files. It's already clear that you can delete all 120Mbytes of unused cities shape files in .../test_data/cities/ .

**Pull request merged**
